# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  ecommersapi:
    image: ecommersapi
    build:
      context: .
      dockerfile: eCommers.Api/Dockerfile
    ports:
      - 8080:8080
